# Generated by Django 2.2.1 on 2022-06-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='castl',
        ),
    ]
