# Generated by Django 2.2.1 on 2022-06-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_order_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='driver_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Not Assigned', 'Not Assigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.Driver'),
        ),
    ]
