# Generated by Django 3.2.9 on 2022-05-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20220515_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='new product',
            field=models.IntegerField(default=0),
        ),
    ]
