# Generated by Django 2.2.1 on 2022-06-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20220614_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_transaction',
            name='Customer_order_id',
        ),
        migrations.DeleteModel(
            name='Customer_order',
        ),
        migrations.DeleteModel(
            name='Customer_Transaction',
        ),
    ]
