# Generated by Django 3.2.9 on 2022-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_auto_20220519_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='beerr',
            field=models.IntegerField(default=0),
        ),
    ]
