# Generated by Django 3.2.9 on 2022-05-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_remove_customer_order_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_transaction',
            old_name='Agent_order_id',
            new_name='Customer_order_id',
        ),
        migrations.AlterField(
            model_name='customer_transaction',
            name='Total_Amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
