# Generated by Django 3.2.9 on 2022-05-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_auto_20220523_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_transaction',
            name='Customer_order_id',
        ),
        migrations.DeleteModel(
            name='Customer_order',
        ),
    ]
