# Generated by Django 3.2.9 on 2022-05-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_delete_customer_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Total_Amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Paid_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=200, null=True)),
                ('TransactionCode', models.CharField(max_length=200, null=True)),
                ('MarchentId', models.CharField(max_length=200, null=True)),
                ('Customer_order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_order')),
            ],
        ),
    ]
