# Generated by Django 3.2.9 on 2022-05-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_customer_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Customer',
        ),
    ]
