# Generated by Django 3.2.9 on 2022-05-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0054_auto_20220522_0018'),
        ('Customer', '0018_auto_20220523_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('Doppel', models.IntegerField(default=0)),
                ('St_George', models.IntegerField(default=0)),
                ('Castle', models.IntegerField(default=0)),
                ('Sinq_Malt', models.IntegerField(default=0)),
                ('beerr', models.IntegerField(default=0)),
                ('NEW', models.IntegerField(default=0)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.customer')),
            ],
        ),
    ]
