# Generated by Django 3.2.9 on 2022-05-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_transaction',
            name='Customer_order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_order'),
        ),
    ]
