# Generated by Django 3.2.9 on 2022-05-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_customer_transaction_customer_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='total_payment',
        ),
    ]
