# Generated by Django 3.2.9 on 2022-05-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_alter_customer_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='driver',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Not Assigned', 'Not Assigned')], max_length=200, null=True),
        ),
    ]
