# Generated by Django 3.2.9 on 2022-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0023_customer_order_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Recived', 'Not Recived'), ('Delivered', 'Delivered')], default='Not Assigned', max_length=200, null=True),
        ),
    ]
