# Generated by Django 3.2.9 on 2022-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_alter_customer_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='NEW',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='beerr',
        ),
    ]
