# Generated by Django 2.2.1 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_remove_agent_order_castl'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='new',
            field=models.IntegerField(default=0),
        ),
    ]
