# Generated by Django 2.2.1 on 2022-06-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_agent_order_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='Full_name',
        ),
    ]
