# Generated by Django 2.2.1 on 2022-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_auto_20220613_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Status',
            field=models.CharField(choices=[('on_duty', 'on_duty'), ('on_garage', 'on_garage'), ('on_wating', 'on_wating')], default='on_wating', max_length=200, null=True),
        ),
    ]
