# Generated by Django 2.2.1 on 2022-06-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_auto_20220613_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.Agent'),
        ),
    ]
