# Generated by Django 2.2.1 on 2022-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0009_auto_20220613_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vichel_No',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
