# Generated by Django 2.2.1 on 2022-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0010_auto_20220614_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vichel_No',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
