# Generated by Django 3.2.9 on 2022-05-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0020_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Agent_Transaction',
        ),
    ]
