# Generated by Django 3.2.9 on 2022-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0021_rename_transaction_agent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_transaction',
            name='Paid_status',
            field=models.CharField(choices=[('Payed', 'Payed'), ('Not Payed', 'Not Payed')], max_length=200, null=True),
        ),
    ]
