# Generated by Django 3.2.9 on 2022-05-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0022_alter_agent_transaction_paid_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
