# Generated by Django 3.2.9 on 2022-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0024_agent_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent_transaction',
            name='Paid_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent_transaction',
            name='TransactionCode',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
