# Generated by Django 3.2.9 on 2022-05-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0025_auto_20220518_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
