# Generated by Django 3.2.9 on 2022-05-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0027_agent_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
