# Generated by Django 3.2.9 on 2022-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0032_auto_20220518_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('Doppel', models.IntegerField(default=0)),
                ('St_George', models.IntegerField(default=0)),
                ('Castle', models.IntegerField(default=0)),
                ('Sinq_Malt', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('newone', models.IntegerField(default=0)),
            ],
        ),
    ]
