# Generated by Django 3.2.9 on 2022-05-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0035_agent_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
