# Generated by Django 3.2.9 on 2022-05-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0074_auto_20220518_2301'),
        ('Agent', '0037_agent_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='new product',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Customers_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=200, null=True)),
                ('mssg', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.agent')),
            ],
        ),
    ]
