# Generated by Django 3.2.9 on 2022-05-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0038_auto_20220518_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_transaction',
            name='Agent_order_id',
        ),
        migrations.DeleteModel(
            name='Agent_order',
        ),
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
