# Generated by Django 3.2.9 on 2022-05-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0074_auto_20220518_2301'),
        ('Agent', '0040_agent_order_agent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_order',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent'),
        ),
    ]
