# Generated by Django 3.2.9 on 2022-05-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0041_alter_agent_order_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_transaction',
            name='Agent_order_id',
        ),
        migrations.DeleteModel(
            name='Agent_order',
        ),
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
