# Generated by Django 3.2.9 on 2022-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0043_agent_order_agent_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='new',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='new product',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='newone',
        ),
    ]
