# Generated by Django 3.2.9 on 2022-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0044_auto_20220519_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_transaction',
            name='Agent_order_id',
        ),
        migrations.DeleteModel(
            name='Agent_order',
        ),
        migrations.DeleteModel(
            name='Agent_Transaction',
        ),
    ]
