# Generated by Django 3.2.9 on 2022-05-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0075_auto_20220519_2314'),
        ('Agent', '0045_auto_20220519_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=200, null=True)),
                ('Doppel', models.IntegerField(default=0)),
                ('St_George', models.IntegerField(default=0)),
                ('Castle', models.IntegerField(default=0)),
                ('Sinq_Malt', models.IntegerField(default=0)),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent')),
                ('Store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company_store')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Total_Amount', models.FloatField(null=True)),
                ('Paid_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=200, null=True)),
                ('TransactionCode', models.CharField(max_length=200, null=True)),
                ('MarchentId', models.CharField(max_length=200, null=True)),
                ('Agent_order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Agent.agent_order')),
            ],
        ),
    ]
