# Generated by Django 3.2.9 on 2022-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0048_agent_order_agent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Recived', 'Recived'), ('Reject', 'Reject')], max_length=200, null=True),
        ),
    ]
