# Generated by Django 3.2.9 on 2022-05-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0085_alter_add_to_store_store'),
        ('Agent', '0051_agent_order_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Telegram',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='about',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instagrm',
        ),
        migrations.AddField(
            model_name='customer',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent'),
        ),
    ]
