# Generated by Django 3.2.9 on 2022-05-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0052_auto_20220521_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Routing',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
