# Generated by Django 3.2.9 on 2022-06-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0055_auto_20220604_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Doppel',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Sinq_Malt',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='St_George',
        ),
    ]
