# Generated by Django 2.2.1 on 2022-06-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='castl',
        ),
    ]
