# Generated by Django 2.2.1 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_remove_product_amount_in_store_castl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='new',
            field=models.IntegerField(default=0),
        ),
    ]
