# Generated by Django 3.2.9 on 2022-05-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0072_auto_20220518_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='customer',
            new_name='user',
        ),
    ]
