# Generated by Django 3.2.9 on 2022-05-19 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0073_rename_customer_messages_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Agents_message',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='new product',
            field=models.IntegerField(default=0),
        ),
    ]
