# Generated by Django 3.2.9 on 2022-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0074_auto_20220518_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='new product',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='newone',
        ),
    ]
