# Generated by Django 3.2.9 on 2022-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0075_auto_20220519_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_store',
            name='Store_Name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
