# Generated by Django 3.2.9 on 2022-05-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0076_alter_company_store_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='data',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='product_photo',
            field=models.ImageField(blank=True, default='Product_img/new.png', null=True, upload_to='Product_img/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
    ]
