# Generated by Django 3.2.9 on 2022-05-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0077_auto_20220520_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agents_message',
        ),
    ]
