# Generated by Django 3.2.9 on 2022-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0079_auto_20220520_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_photo', models.ImageField(blank=True, default='Product_img/new.png', null=True, upload_to='Product_img/')),
            ],
        ),
    ]
