# Generated by Django 3.2.9 on 2022-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0080_advertisment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='beerr',
            field=models.IntegerField(default=0),
        ),
    ]
