# Generated by Django 3.2.9 on 2022-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0081_product_amount_in_store_beerr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='NEW',
            field=models.IntegerField(default=0),
        ),
    ]
