# Generated by Django 3.2.9 on 2022-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0085_alter_add_to_store_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='NEW',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='beerr',
        ),
    ]
