# Generated by Django 3.2.9 on 2022-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0086_auto_20220604_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
