# Generated by Django 3.2.9 on 2022-06-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0088_agent_marchentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.region'),
        ),
    ]
