# Generated by Django 3.2.9 on 2022-06-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0089_alter_agent_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_store_manager',
            old_name='Adderes',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='company_store_manager',
            old_name='instagrm',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='finance_manager',
            old_name='Adderes',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='finance_manager',
            old_name='instagrm',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='company_store_manager',
            name='Full_Name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='finance_manager',
            name='Full_Name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company_store_manager',
            name='Store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company_store'),
        ),
    ]
