# Generated by Django 3.2.9 on 2022-06-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0090_auto_20220606_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_manager',
            old_name='Telegram',
            new_name='telegram',
        ),
    ]
