# Generated by Django 3.2.9 on 2022-06-09 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0092_auto_20220606_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Doppel',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Sinq_Malt',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='St_George',
        ),
        migrations.AlterField(
            model_name='company_store_manager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
